version: "3.8"
services:
  db:
    image: postgres:16
    container_name: userapi-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
    volumes: [db_data:/var/lib/postgresql/data]

  app:                       # ← НОВЫЙ блок
    image: userapi:latest    # контейнер, который мы собрали
    build: .                 # чтобы compose мог сам пересобирать
    depends_on: [db]
    ports: ["8080:8080"]     # прокидываем наружу
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret

volumes:
  db_data:
