spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5m
server:
  port: 8080